strictness: medium
autodetect: yes
ignore-paths:
  - src/Analysis/peepdf/
  - src/Logging/modules/MITRE/MAEC_v1_1.py
  - src/Logging/modules/MITRE/MAEC_v4_0.py
  - tools/checkinstall.py
  - samples/steps/exploits.py
  - samples/steps/misc.py
  - src/ThugAPI/IThugAPI.py
  - src/Plugins/IPlugin.py
pylint:
  disable:
    - too-many-arguments
